# Generated by Django 2.2b1 on 2019-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_mrp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopclues',
            name='prod_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_mrp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_price',
            field=models.IntegerField(default=0),
        ),
    ]
