# Generated by Django 2.2b1 on 2019-06-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0004_auto_20190610_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_specs_left',
            field=models.CharField(default='Not Available', max_length=500),
        ),
        migrations.AddField(
            model_name='shopclues',
            name='prod_specs_right',
            field=models.CharField(default='Not Available', max_length=500),
        ),
    ]
