# Generated by Django 2.2b1 on 2019-06-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0006_auto_20190611_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapdeal',
            name='prod_specs_left',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_specs_right',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_URL',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_mrp',
            field=models.CharField(default='Not Available', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_name',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_price',
            field=models.CharField(default='Not Available', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_specs_left',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_specs_right',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_URL',
            field=models.CharField(default='www.Snapdeal.com', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_mrp',
            field=models.CharField(default='Not Available', max_length=10),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_name',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_price',
            field=models.CharField(default='Not Available', max_length=10),
        ),
    ]
