# Generated by Django 2.2b1 on 2019-06-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0007_auto_20190611_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_First_Category',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='shopclues',
            name='prod_Second_Category',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='shopclues',
            name='prod_Third_Category',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_First_Category',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_Second_Category',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_Third_Category',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
