# Generated by Django 2.2b1 on 2019-06-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0009_auto_20190611_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopclues',
            name='prod_specs_left',
        ),
        migrations.RemoveField(
            model_name='shopclues',
            name='prod_specs_right',
        ),
        migrations.RemoveField(
            model_name='snapdeal',
            name='prod_specs_left',
        ),
        migrations.RemoveField(
            model_name='snapdeal',
            name='prod_specs_right',
        ),
    ]
