# Generated by Django 2.2b1 on 2019-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0011_auto_20190611_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclues',
            name='prod_name',
            field=models.CharField(default='Not Available', max_length=150),
        ),
    ]
