# Generated by Django 2.2b1 on 2019-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0014_auto_20190612_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclues',
            name='prod_specs_left',
            field=models.CharField(default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_specs_right',
            field=models.CharField(default=None, max_length=4000, null=True),
        ),
    ]
