# Generated by Django 2.2b1 on 2019-06-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0018_auto_20190612_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopclue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default='Not Available', max_length=100)),
                ('prod_price', models.CharField(default='Not Available', max_length=10)),
                ('prod_mrp', models.CharField(default='Not Available', max_length=10)),
                ('prod_URL', models.CharField(default='www.Snapdeal.com', max_length=200, null=True)),
                ('prod_First_Category', models.CharField(default=None, max_length=100, null=True)),
                ('prod_Second_Category', models.CharField(default=None, max_length=100, null=True)),
                ('prod_Third_Category', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
