# Generated by Django 2.2b1 on 2019-06-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0021_auto_20190613_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclue',
            name='prod_specs_left',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shopclue',
            name='prod_specs_right',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
