# Generated by Django 2.2b1 on 2019-06-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0025_auto_20190614_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_description',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_highlights',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
