# Generated by Django 2.2b1 on 2019-06-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0026_auto_20190614_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclues',
            name='prod_mrp',
            field=models.CharField(default='Not Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_price',
            field=models.CharField(default='Not Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_mrp',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_price',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
