# Generated by Django 2.2b1 on 2019-06-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0028_auto_20190618_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclue',
            name='prod_image_URL',
            field=models.CharField(default=True, max_length=400, null=True),
        ),
    ]
