# Generated by Django 2.2b1 on 2019-06-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0029_shopclue_prod_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclue',
            name='prod_URL',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_image_URL',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
