# Generated by Django 2.2b1 on 2019-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0030_auto_20190621_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapdeal',
            name='prod_image_URL',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
