# Generated by Django 2.2b1 on 2019-06-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0031_snapdeal_prod_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_URL',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
    ]
