# Generated by Django 2.2b1 on 2019-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0032_auto_20190622_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default=None, max_length=1000, null=True)),
                ('prod_price', models.CharField(default=None, max_length=50, null=True)),
                ('prod_mrp', models.CharField(default=None, max_length=50, null=True)),
                ('prod_availi', models.CharField(default=None, max_length=100, null=True)),
                ('prod_URL', models.CharField(default=None, max_length=800, null=True)),
                ('prod_specs_left', models.CharField(default=None, max_length=8000, null=True)),
                ('prod_specs_right', models.CharField(default=None, max_length=8000, null=True)),
                ('prod_First_Category', models.CharField(default=None, max_length=100, null=True)),
                ('prod_Second_Category', models.CharField(default=None, max_length=100, null=True)),
                ('prod_Third_Category', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_mrp',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_price',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_mrp',
            field=models.CharField(default='Not Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_price',
            field=models.CharField(default='Not Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_mrp',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_price',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
