# Generated by Django 2.2.3 on 2019-07-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0033_auto_20190625_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclue',
            name='prod_ratings',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='shopclue',
            name='prod_reviews',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
