# Generated by Django 2.2.3 on 2019-07-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0042_auto_20190704_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazon',
            old_name='prod_ratings_FeatureFive',
            new_name='prod_ratings_FeatureKey',
        ),
        migrations.RenameField(
            model_name='amazon',
            old_name='prod_ratings_FeatureFour',
            new_name='prod_ratings_FeatureValue',
        ),
        migrations.RemoveField(
            model_name='amazon',
            name='prod_ratings_FeatureOne',
        ),
        migrations.RemoveField(
            model_name='amazon',
            name='prod_ratings_FeatureThree',
        ),
        migrations.RemoveField(
            model_name='amazon',
            name='prod_ratings_FeatureTwo',
        ),
    ]
