# Generated by Django 2.2.3 on 2019-07-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0045_auto_20190705_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='prod_URL',
            field=models.CharField(default=None, max_length=80000, null=True),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='prod_image_URL',
            field=models.CharField(default=None, max_length=90000, null=True),
        ),
    ]
