# Generated by Django 2.2.3 on 2019-07-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0046_auto_20190705_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='prod_ratings_FeatureKey',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='prod_ratings_FeatureValue',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
