# Generated by Django 2.2.3 on 2019-07-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0050_auto_20190709_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_image_url',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
