# Generated by Django 2.2.3 on 2019-07-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0054_auto_20190722_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclues',
            name='prod_temp_name',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
