# Generated by Django 2.2.3 on 2019-07-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0055_auto_20190722_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclue',
            name='prod_temp_name',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_temp_name',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
