# Generated by Django 2.2.3 on 2019-07-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0056_auto_20190722_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_display_image_URL',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
