# Generated by Django 2.2.3 on 2019-07-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0057_shopclues_prod_display_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_ratings',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopclues',
            name='prod_reviews',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
