# Generated by Django 2.2.3 on 2019-07-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0061_auto_20190723_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='prod_temp_name',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
