# Generated by Django 2.2.3 on 2019-07-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0062_amazon_prod_temp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapdeal',
            name='prod_overall',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
