# Generated by Django 2.2.3 on 2019-07-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0063_snapdeal_prod_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclue',
            name='prod_overall',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
