# Generated by Django 2.2.3 on 2019-08-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0065_auto_20190729_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='prod_First_Category',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_Second_Category',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
