# Generated by Django 2.2.3 on 2019-10-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0068_amazon_prod_top_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclue',
            name='prod_top_Category',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
