# Generated by Django 2.2.3 on 2019-11-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0077_auto_20191107_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclue',
            name='prod_Date',
            field=models.CharField(default='2019-11-08', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shopclues',
            name='prod_Date',
            field=models.CharField(default='2019-11-08', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_Date',
            field=models.CharField(default='2019-11-08', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='prod_Date',
            field=models.CharField(default='2019-11-08', max_length=20, null=True),
        ),
    ]
