# Generated by Django 2.1 on 2020-01-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0080_auto_20200116_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='prod_Date',
            field=models.CharField(default='2020-01-19', max_length=20, null=True),
            
        ),
        migrations.AlterField(
            model_name='amazon',
            name='prod_affiliate_URL',
            field=models.CharField(default='None',max_length=500,null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_Date',
            field=models.CharField(default='2020-01-19', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_Date',
            field=models.CharField(default='2020-01-19', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_Date',
            field=models.CharField(default='2020-01-19', max_length=20, null=True),
        ),
    ]
