# Generated by Django 2.1 on 2020-01-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0082_auto_20200122_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='prod_Date',
            field=models.CharField(default='2020-01-22', max_length=20, null=True),
        ),
    ]
