# Generated by Django 2.1 on 2020-01-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0083_auto_20200122_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='prod_affiliate_URL',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
