# Generated by Django 2.2.3 on 2020-06-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0084_amazon_prod_affiliate_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='prod_Date',
            field=models.CharField(default='2020-06-05', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_Date',
            field=models.CharField(default='2020-06-05', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_Date',
            field=models.CharField(default='2020-06-05', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_Date',
            field=models.CharField(default='2020-06-05', max_length=20, null=True),
        ),
    ]
