# Generated by Django 2.2b1 on 2019-06-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0003_auto_20190610_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_URL',
            field=models.CharField(default='www.Shopclues.com', max_length=200),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_URL',
            field=models.CharField(default='www.Snapdeal.com', max_length=200),
        ),
    ]
