# Generated by Django 2.2b1 on 2019-06-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0005_auto_20190611_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclues',
            name='prod_URL',
            field=models.CharField(default='www.Shopclues.com', max_length=400),
        ),
    ]
