# Generated by Django 2.2b1 on 2019-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0017_auto_20190612_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default='Not Available', max_length=100)),
                ('prod_price', models.CharField(default='Not Available', max_length=10)),
                ('prod_mrp', models.CharField(default='Not Available', max_length=10)),
                ('prod_URL', models.CharField(default='www.Snapdeal.com', max_length=200, null=True)),
                ('prod_First_Category', models.CharField(default=None, max_length=100, null=True)),
                ('prod_Second_Category', models.CharField(default=None, max_length=100, null=True)),
                ('prod_Third_Category', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Flipkart',
        ),
        migrations.AddField(
            model_name='shopclues',
            name='prod_specs_left',
            field=models.CharField(default=None, max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='shopclues',
            name='prod_specs_right',
            field=models.CharField(default=None, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_URL',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_name',
            field=models.CharField(default='Not Available', max_length=150),
        ),
    ]
