# Generated by Django 2.2b1 on 2019-06-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0019_shopclue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclue',
            name='prod_mrp',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_price',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
