# Generated by Django 2.2b1 on 2019-06-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0020_auto_20190613_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclue',
            name='prod_URL',
            field=models.CharField(default='www.Snapdeal.com', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_mrp',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_price',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_name',
            field=models.CharField(default='Not Available', max_length=200),
        ),
    ]
