# Generated by Django 2.2b1 on 2019-06-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0022_auto_20190613_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclue',
            name='prod_URL',
            field=models.CharField(default='www.Snapdeal.com', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_name',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_URL',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_name',
            field=models.CharField(default='Not Available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_URL',
            field=models.CharField(default='www.Snapdeal.com', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_name',
            field=models.CharField(default='Not Available', max_length=1000),
        ),
    ]
