# Generated by Django 2.2b1 on 2019-06-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0023_auto_20190613_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapdeal',
            name='prod_description',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_highlights',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_specs_left',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_specs_right',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
