# Generated by Django 2.2b1 on 2019-06-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0024_auto_20190614_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_mrp',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_name',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_price',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
