# Generated by Django 2.2b1 on 2019-06-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0027_auto_20190618_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclue',
            name='prod_specs_left',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_specs_right',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_specs_left',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_specs_right',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
