# Generated by Django 2.2.3 on 2019-07-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0034_auto_20190702_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapdeal',
            name='prod_ratings',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_reviews',
            field=models.CharField(default=True, max_length=300, null=True),
        ),
    ]
