# Generated by Django 2.2.3 on 2019-07-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0035_auto_20190703_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_reviews',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
