# Generated by Django 2.2.3 on 2019-07-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0036_auto_20190703_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapdeal',
            name='prod_reviews',
        ),
    ]
