# Generated by Django 2.2.3 on 2019-07-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0038_snapdeal_prod_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='prod_description',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_specifications',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
