# Generated by Django 2.2.3 on 2019-07-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0039_auto_20190703_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='prod_description',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='prod_specifications',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='prod_specs_left',
            field=models.CharField(default=None, max_length=80000, null=True),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='prod_specs_right',
            field=models.CharField(default=None, max_length=80000, null=True),
        ),
    ]
