# Generated by Django 2.2.3 on 2019-07-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0040_auto_20190704_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='prod_availi',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
