# Generated by Django 2.2.3 on 2019-07-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0041_auto_20190704_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='prod_ratings_1start',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_ratings_2start',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_ratings_3start',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_ratings_4start',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_ratings_5start',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_ratings_FeatureFive',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_ratings_FeatureFour',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_ratings_FeatureOne',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_ratings_FeatureThree',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_ratings_FeatureTwo',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazon',
            name='prod_reviews',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
