# Generated by Django 2.2.3 on 2019-07-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0043_auto_20190704_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='prod_image_URL',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
