# Generated by Django 2.2.3 on 2019-07-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0044_amazon_prod_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon',
            name='prod_First_Category',
        ),
        migrations.RemoveField(
            model_name='amazon',
            name='prod_Second_Category',
        ),
        migrations.RemoveField(
            model_name='amazon',
            name='prod_Third_Category',
        ),
    ]
