# Generated by Django 2.2.3 on 2019-07-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0047_auto_20190705_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_url_title',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
