# Generated by Django 2.2.3 on 2019-07-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0048_shopclues_prod_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclue',
            name='prod_url_title',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
