# Generated by Django 2.2.3 on 2019-07-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0049_shopclue_prod_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='prod_url_title',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='snapdeal',
            name='prod_url_title',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
