# Generated by Django 2.2.3 on 2019-07-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0052_auto_20190722_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_temp_name',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
