# Generated by Django 2.2.3 on 2019-07-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0053_shopclues_prod_temp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclues',
            name='prod_mrp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_name',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
