# Generated by Django 2.2.3 on 2019-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0058_auto_20190722_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_overall',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopclues',
            name='prod_star',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
