# Generated by Django 2.2.3 on 2019-07-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0060_auto_20190722_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclues',
            name='prod_star',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
