# Generated by Django 2.2.3 on 2019-07-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0064_shopclue_prod_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclue',
            name='prod_name',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
