# Generated by Django 2.2.3 on 2019-10-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0066_auto_20190804_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_top_Category',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
