# Generated by Django 2.2.3 on 2019-10-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0070_snapdeal_prod_top_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclues',
            name='prod_page_URL',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
