# Generated by Django 2.2.3 on 2019-10-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0071_shopclues_prod_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='prod_page_URL',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
