# Generated by Django 2.2.3 on 2019-10-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0072_amazon_prod_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapdeal',
            name='prod_page_url',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
