# Generated by Django 2.2.3 on 2019-10-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0073_snapdeal_prod_page_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapdeal',
            old_name='prod_page_url',
            new_name='prod_page_URL',
        ),
    ]
