# Generated by Django 2.2.3 on 2019-10-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0074_auto_20191027_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclue',
            name='prod_page_URL',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
