# Generated by Django 2.2.3 on 2019-11-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0075_shopclue_prod_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='prod_Date',
            field=models.CharField(default='2019-11-07 23:12:23.255977', max_length=20, null=True),
        ),
    ]
