# Generated by Django 2.2.3 on 2019-11-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0076_amazon_prod_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='prod_Date',
            field=models.CharField(default='2019-11-07', max_length=20, null=True),
        ),
    ]
