# Generated by Django 2.1 on 2019-11-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageScrape', '0078_auto_20191108_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='prod_Date',
            field=models.CharField(default='2019-11-24', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopclue',
            name='prod_Date',
            field=models.CharField(default='2019-11-24', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopclues',
            name='prod_Date',
            field=models.CharField(default='2019-11-24', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='snapdeal',
            name='prod_Date',
            field=models.CharField(default='2019-11-24', max_length=20, null=True),
        ),
    ]
